In [1]:
import pandas as pd
import numpy as np

#Create a series with 100 random numbers
s = pd.Series(np.random.randn(4))
s

0   -0.471770
1   -1.010535
2   -0.623283
3    0.423535
dtype: float64

In [2]:
s = pd.Series(np.random.randn(4))
print ("The axes are:")
s.axes

The axes are:

[RangeIndex(start=0, stop=4, step=1)]

In [3]:
s = pd.Series(np.random.randn(4))
print ("Is the Object empty?")
s.empty

Is the Object empty?

False

In [4]:
s = pd.Series(np.random.randn(4))

print ("The dimensions of the object:")
s.ndim

The dimensions of the object:

1

In [5]:
s = pd.Series(np.random.randn(2))

print ("The size of the object:")
s.size

The size of the object:

2

In [7]:
s = pd.Series(np.random.randn(4))


print ("The actual data series is:")
s.values

The actual data series is:

array([0.99243986, 2.23221877, 1.30286408, 0.55249955])

In [9]:
s = pd.Series(np.random.randn(4))
print ("The original series is:")


print ("The first two rows of the data series:")
s.head(2)

The original series is:
The first two rows of the data series:

0    1.865566
1    0.052888
dtype: float64

In [11]:
s = pd.Series(np.random.randn(4))
print ("The original series is:")


print ("The last two rows of the data series:")
s.tail(2)

The original series is:
The last two rows of the data series:

2   -0.411255
3   -0.798587
dtype: float64

# Function Apply In **DataFrame**

In [12]:
d = {'Name':pd.Series(['Tom','James','Ricky','Vin','Steve','Smith','Jack']),
   'Age':pd.Series([25,26,25,23,30,29,23]),
   'Rating':pd.Series([4.23,3.24,3.98,2.56,3.20,4.6,3.8])}

#Create a DataFrame
df = pd.DataFrame(d)
print ("Our data series is:")
df

Our data series is:

    Name  Age  Rating
0    Tom   25    4.23
1  James   26    3.24
2  Ricky   25    3.98
3    Vin   23    2.56
4  Steve   30    3.20
5  Smith   29    4.60
6   Jack   23    3.80

# The transpose of the data series is:**bold text**

In [13]:
df.T

           0      1      2     3      4      5     6
Name     Tom  James  Ricky   Vin  Steve  Smith  Jack
Age       25     26     25    23     30     29    23
Rating  4.23   3.24   3.98  2.56    3.2    4.6   3.8

In [14]:
d = {'Name':pd.Series(['Tom','James','Ricky','Vin','Steve','Smith','Jack']),
   'Age':pd.Series([25,26,25,23,30,29,23]),
   'Rating':pd.Series([4.23,3.24,3.98,2.56,3.20,4.6,3.8])}

#Create a DataFrame
df = pd.DataFrame(d)
print ("Row axis labels and column axis labels are:")
df.axes

Row axis labels and column axis labels are:

[RangeIndex(start=0, stop=7, step=1),
 Index(['Name', 'Age', 'Rating'], dtype='object')]

In [15]:
d = {'Name':pd.Series(['Tom','James','Ricky','Vin','Steve','Smith','Jack']),
   'Age':pd.Series([25,26,25,23,30,29,23]),
   'Rating':pd.Series([4.23,3.24,3.98,2.56,3.20,4.6,3.8])}

#Create a DataFrame
df = pd.DataFrame(d)
print ("The data types of each column are:")
df.dtypes

The data types of each column are:

Name       object
Age         int64
Rating    float64
dtype: object

In [16]:
df.empty

False

In [17]:
df.ndim

2

In [18]:
df.shape

(7, 3)

In [19]:
df.size

21

In [20]:
df.values

array([['Tom', 25, 4.23],
       ['James', 26, 3.24],
       ['Ricky', 25, 3.98],
       ['Vin', 23, 2.56],
       ['Steve', 30, 3.2],
       ['Smith', 29, 4.6],
       ['Jack', 23, 3.8]], dtype=object)

In [21]:
df.head()

    Name  Age  Rating
0    Tom   25    4.23
1  James   26    3.24
2  Ricky   25    3.98
3    Vin   23    2.56
4  Steve   30    3.20

In [22]:
df.tail()

    Name  Age  Rating
2  Ricky   25    3.98
3    Vin   23    2.56
4  Steve   30    3.20
5  Smith   29    4.60
6   Jack   23    3.80

In [23]:
df.head(3)

    Name  Age  Rating
0    Tom   25    4.23
1  James   26    3.24
2  Ricky   25    3.98