In [2]:
import pandas as pd
import numpy as np

N=20

df = pd.DataFrame({
   'A': pd.date_range(start='2016-01-01',periods=N,freq='D'),
   'x': np.linspace(0,stop=N-1,num=N),
   'y': np.random.rand(N),
   'C': np.random.choice(['Low','Medium','High'],N).tolist(),
   'D': np.random.normal(100, 10, size=(N)).tolist()
})

df

            A     x         y       C           D
0  2016-01-01   0.0  0.507801    High  102.220994
1  2016-01-02   1.0  0.173283  Medium   98.693697
2  2016-01-03   2.0  0.712140     Low   99.453786
3  2016-01-04   3.0  0.592576     Low  101.527603
4  2016-01-05   4.0  0.857091     Low   80.166153
5  2016-01-06   5.0  0.656097    High  120.296905
6  2016-01-07   6.0  0.716205  Medium   96.915209
7  2016-01-08   7.0  0.129175     Low   92.455767
8  2016-01-09   8.0  0.121030  Medium  102.998574
9  2016-01-10   9.0  0.878853  Medium   86.998044
10 2016-01-11  10.0  0.091498  Medium   90.719070
11 2016-01-12  11.0  0.213560     Low   83.936324
12 2016-01-13  12.0  0.255778  Medium   93.947539
13 2016-01-14  13.0  0.276601     Low  115.602584
14 2016-01-15  14.0  0.630762  Medium   88.633790
15 2016-01-16  15.0  0.130236  Medium  104.778112
16 2016-01-17  16.0  0.878316     Low  103.919066
17 2016-01-18  17.0  0.079022  Medium   97.238914
18 2016-01-19  18.0  0.132905     Low   95.690090
19 2016-01-20  19.0  0.416830    High   93.687748

In [3]:
df_reindexed = df.reindex(index=[0,2,5], columns=['A', 'C', 'B'])
df_reindexed

           A     C   B
0 2016-01-01  High NaN
2 2016-01-03   Low NaN
5 2016-01-06  High NaN

In [4]:
df1 = pd.DataFrame(np.random.randn(10,3),columns=['col1','col2','col3'])
df2 = pd.DataFrame(np.random.randn(7,3),columns=['col1','col2','col3'])

df1 = df1.reindex_like(df2)
df1

       col1      col2      col3
0 -0.072782  0.541626 -0.764050
1  1.365858  0.437972 -0.455544
2 -0.670497 -0.627513  1.639443
3 -0.904154 -1.582584  1.029441
4  0.243167 -0.371205  0.116676
5 -0.394927 -0.565348  0.632591
6 -1.759872 -1.177232 -0.500361

In [5]:
df1 = pd.DataFrame(np.random.randn(6,3),columns=['col1','col2','col3'])
df2 = pd.DataFrame(np.random.randn(2,3),columns=['col1','col2','col3'])

# Padding NAN's
print (df2.reindex_like(df1))

# Now Fill the NAN's with preceding Values
print ("Data Frame with Forward Fill:")
df2.reindex_like(df1,method='ffill')

       col1      col2      col3
0 -0.391571  0.221852  0.007758
1  0.914529  1.229274 -0.051734
2       NaN       NaN       NaN
3       NaN       NaN       NaN
4       NaN       NaN       NaN
5       NaN       NaN       NaN
Data Frame with Forward Fill:

       col1      col2      col3
0 -0.391571  0.221852  0.007758
1  0.914529  1.229274 -0.051734
2  0.914529  1.229274 -0.051734
3  0.914529  1.229274 -0.051734
4  0.914529  1.229274 -0.051734
5  0.914529  1.229274 -0.051734

In [7]:
df2.reindex_like(df1,method='ffill',limit=1)

       col1      col2      col3
0 -0.391571  0.221852  0.007758
1  0.914529  1.229274 -0.051734
2  0.914529  1.229274 -0.051734
3       NaN       NaN       NaN
4       NaN       NaN       NaN
5       NaN       NaN       NaN

In [8]:
df1 = pd.DataFrame(np.random.randn(6,3),columns=['col1','col2','col3'])
print (df1)

print ("After renaming the rows and columns:")
df1.rename(columns={'col1' : 'c1', 'col2' : 'c2'},
index = {0 : 'apple', 1 : 'banana', 2 : 'durian'})

       col1      col2      col3
0  0.397088  2.408168  0.566415
1  0.984062 -0.017940 -1.026559
2  1.125090 -0.791886 -0.115020
3 -1.238763 -0.331876 -0.317843
4  0.879759 -1.631790  2.452626
5 -1.316943  0.304735 -0.442070
After renaming the rows and columns:

              c1        c2      col3
apple   0.397088  2.408168  0.566415
banana  0.984062 -0.017940 -1.026559
durian  1.125090 -0.791886 -0.115020
3      -1.238763 -0.331876 -0.317843
4       0.879759 -1.631790  2.452626
5      -1.316943  0.304735 -0.442070